# Generated by Django 2.0.5 on 2018-07-25 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answerclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ans', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateField(default=datetime.datetime(2018, 7, 25, 16, 48, 51, 623346, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to='profile_pic')),
                ('user_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.user_info'),
        ),
        migrations.AddField(
            model_name='answerclass',
            name='author_ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to='cloneapp.user_info'),
        ),
        migrations.AddField(
            model_name='answerclass',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ans', to='cloneapp.question'),
        ),
    ]
