# Generated by Django 2.0.5 on 2018-07-28 06:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='home',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='studies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='work',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 6, 53, 59, 145038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='image_field',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinf', to=settings.AUTH_USER_MODEL),
        ),
    ]
