# Generated by Django 2.1 on 2018-09-06 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0002_auto_20180728_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 6, 13, 26, 8, 89478, tzinfo=utc)),
        ),
    ]
